#!/usr/bin/env sh
# Get the real installation directory
DIR="$(dirname "$(readlink -f "$0")")/"

exec node --max-old-space-size=76 \
          --max-semi-space-size=2 \
          --expose-gc \
          --v8-pool-size=0 \
          --optimize-for-size \
          --no-compilation-cache \
          "$DIR/index.js" "$@"
